name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: yarn install

      - name: Build for Windows
        run: yarn run build:win

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Windows Build
          path: dist/

  create_release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.KIOSK_SECRETS }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release ${{ github.ref }}
            Auto-generated release by GitHub Actions
          draft: false
          prerelease: false

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: Windows Build
          path: dist/

      - name: Create Zip Archive
        run: |
          cd dist
          zip -r ../${{ github.ref }}.zip .
        working-directory: ${{ github.workspace }}

      - name: Upload Release Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.KIOSK_SECRETS }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ github.ref }}.zip
          asset_name: ${{ github.ref }}.zip
          asset_content_type: application/zip
